### ISSUE TITLE
do. we need caching for responses

### ISSUE THREAD

**Issue by dil-kkumar** [mikeebowen/node-wopi-server#5]

**Comment by dil-kkumar** [comment]
M365 sometimes loading the data and sometimes not.

**Comment by mikeebowen** [comment]
Hi @dil-kkumar, I don't understand the question. Could you please explain with more detail what you're asking.

**Comment by dil-kkumar** [comment]
we have implemented WOPI Integration using this project. 
Microsoft server calling the Wopi server very frequently, sometimes online editor is loading with empty and writing to the file also not stable.

**Comment by mikeebowen** [comment]
This repo is meant to be a demonstration of how a WOPI server should respond to requests from Office Online Server/Office for the web when implementing the [WOPI protocol](https://learn.microsoft.com/en-us/microsoft-365/cloud-storage-partner-program/online/). It is NOT production ready and is meant to be used as a guide to developers implementing the WOPI protocol. This repo is free and open-source, so you are free to use it in concurrence with the MIT license, but be aware aspects unrelated to the WOPI protocol, such as authentication and file saving, are faked or done in an unsecure way, to simplify the process and focus on the WOPI protocol implementation and MUST be replaced by your own implementation if you plan to use this in production, so unfortunately the file saving and loading issues are an implementation detail that you will have to resolve in your implementation.

For the frequent calls, it is expected for Office Online Server/Office for the web to call the WOPI server relatively frequently, e.g. it saves at regular intervals depending on the file type (the intervals are [explained here](https://learn.microsoft.com/en-us/microsoft-365/cloud-storage-partner-program/online/scenarios/coauth#how-co-authoring-works-in-office-for-the-web)), so this is likely expected behavior. To help investigate this (and WOPI integration in general) [Fiddler classic](https://www.telerik.com/download/fiddler) set up to use a [reverse proxy](https://docs.telerik.com/fiddler/configure-fiddler/tasks/usefiddlerasreverseproxy) to your WOPI server port can be helpful.
