### ISSUE TITLE
Error While opening the file.

### ISSUE THREAD

**Issue by priyanshumaurya007** [mikeebowen/node-wopi-server#6]
I'm using blob storage to retrieve the files. Implemented all the file operations where it is checkFileInfo, getfile or any lock operation but unable to open the file in edit or view mode. I can see file name and favico of extension type.

<img width="952" alt="image" src="https://github.com/mikeebowen/node-wopi-server/assets/74262554/c05bdfda-d2e7-45c9-9c2f-49047ecc7b45">
<img width="956" alt="image" src="https://github.com/mikeebowen/node-wopi-server/assets/74262554/7388b739-770c-4933-bfa6-cfab686dd259">

**Comment by mikeebowen** [comment]
This repo is to demonstrate how to implement the WOPI protocol and is not meant for production or as a demonstration on how to retrieve files. In this example implementation, it simply reads and saves files to disk directly. If you have issues with retrieving your files then the issue is somewhere in your file retrieval implementation and not with the WOPI protocol. I'm sorry, but there's nothing we can do to help with your issue.
